typography_spectrum: 0.7486952445469797
content_rating:
  adult: false
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9962832240853459
  lightness: 0.07766973902471364
  saturation: 0.6143763686995953
  rhythmicContrast: 0.015534949023276567
github: true
opengraph:
  type: ''
  appId: ''
  image: null
layout_spectrum: 0.5679895360954106
analytics:
  facebook: ''
  google: UA-62609309-1
  twitter: 2@nikswebdesign
author:
  name: Ralph Nicolay
  url: ''
  email: ralphontheship@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/969e12d5-3eda-4329-b321-69fb165a425c.png
name: Niks Photography
navigation:
  - name: Photography
    id: 955fac7a-4395-492a-8413-99c987771ff5
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e6efbdd5-92bb-43b3-99e8-d728399e8a90.gif
title: The Drive for Perfection
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/9e776146-2376-4345-8d96-aec39170c61b.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/9e776146-2376-4345-8d96-aec39170c61b.jpg
    metadata:
      author: []
      related: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      keywords: []
      description: ''
      app_links: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      datePublished: null
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: 'Photography '
purpose:
  - type: contact
    url: 'mailto:ralphontheship@gmail.com'
    label: Contact us
