typography_spectrum: 0.7486952445469797
content_rating:
  adult: false
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.9962832240853459
  lightness: 0.07766973902471364
  saturation: 0.6143763686995953
  rhythmicContrast: 0.015534949023276567
github: true
opengraph:
  type: ''
  appId: ''
  image: null
layout_spectrum: 0.5679895360954106
analytics:
  facebook: ''
  google: UA-62609309-1
  twitter: 2@nikswebdesign
author:
  name: Ralph Nicolay
  url: ''
  email: ralphontheship@gmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/969e12d5-3eda-4329-b321-69fb165a425c.png
name: Niks Photography
navigation:
  - name: Photography
    id: 955fac7a-4395-492a-8413-99c987771ff5
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e6efbdd5-92bb-43b3-99e8-d728399e8a90.gif
title: Niks Photography
content: []
description: Examples
purpose:
  - type: contact
    url: 'mailto:ralphontheship@gmail.com'
    label: E-mail Me
  - type: internal
    label: Let's Begin
    item: d04b0f88-458b-40fd-a0ce-6c877f113fc9
