typography_spectrum: 0.7486952445469797
color:
  brandStrength: 0.9962832240853459
  lightness: 0.07766973902471364
  saturation: 0.6143763686995953
  rhythmicContrast: 0.015534949023276567
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
github: true
opengraph:
  image: >-
    https://the-grid-user-content.s3-us-west-2.amazonaws.com/4bd2bac9-be63-4c10-a3ad-42f437e975ff.jpg
layout_spectrum: 0.5679895360954106
analytics:
  twitter: 2@nikswebdesign
  google: UA-62609309-1
author:
  name: Ralph Nicolay
  email: ralph.nicolay@nikswebdesign.com
  url: www.nikswebdesign.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/969e12d5-3eda-4329-b321-69fb165a425c.png
name: 'Niks '
navigation:
  - name: Photography
    id: 955fac7a-4395-492a-8413-99c987771ff5
    type: content
  - name: Illustration
    id: a87523ce-382c-4821-b6d2-44fdf7def015
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/e6efbdd5-92bb-43b3-99e8-d728399e8a90.gif
title: 'Web Design and Photography, LLC'
description: Photography for all your needs
purpose:
  - type: contact
    url: 'mailto:ralph.nicolay@nikswebdesign.com'
    label: Contact me
